/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.kasirdigital;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author IDEAPAD
 */
public class FormLaporan extends javax.swing.JFrame {
    private void load_laporan() {
     DefaultTableModel model = new DefaultTableModel();
     model.addColumn("No Transaksi");
     model.addColumn("Tanggal");
     model.addColumn("Total Belanja");
     model.addColumn("Bayar");
     model.addColumn("Kembalian");

     try {
         // Mengambil data dari tabel transaksi di database
         String sql = "SELECT * FROM tb_transaksi ORDER BY tanggal DESC"; 
         Connection conn = KoneksiDB.getKoneksi();
         Statement stm = conn.createStatement();
         ResultSet res = stm.executeQuery(sql);

         while (res.next()) {
             model.addRow(new Object[]{
                 res.getString("no_transaksi"),
                 res.getString("tanggal"),
                 res.getString("total_belanja"),
                 res.getString("bayar"),
                 res.getString("kembalian")
             });
         }
         tblLaporan.setModel(model);
     } catch (Exception e) {
         JOptionPane.showMessageDialog(this, "Gagal memuat laporan: " + e.getMessage());
     }
 }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormLaporan.class.getName());

    /**
     * Creates new form FormLaporan
     */
    public FormLaporan() {
     initComponents();
     load_laporan(); // Tambahkan baris ini
     getContentPane().setBackground(java.awt.Color.decode("#00BFFF"));
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLaporan = new javax.swing.JTable();
        btnCetak = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LAPORAN PENJUALAN HARIAN");

        tblLaporan.setBackground(new java.awt.Color(255, 153, 51));
        tblLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No Transaksi", "Tanggal", "Total Belanja", "Bayar", "Kembalian"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLaporan);

        btnCetak.setBackground(new java.awt.Color(255, 153, 51));
        btnCetak.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCetak.setForeground(new java.awt.Color(255, 255, 255));
        btnCetak.setText("CETAK LAPORAN");
        btnCetak.addActionListener(this::btnCetakActionPerformed);

        btnKembali.setBackground(new java.awt.Color(255, 153, 51));
        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("KEMBALI KEMENU");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btnCetak)
                        .addGap(109, 109, 109)
                        .addComponent(btnKembali)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCetak)
                    .addComponent(btnKembali))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        com.lowagie.text.Document document = new com.lowagie.text.Document(com.lowagie.text.PageSize.A4);
        try {
            String namaFile = "Laporan_Penjualan.pdf";
            com.lowagie.text.pdf.PdfWriter.getInstance(document, new java.io.FileOutputStream(namaFile));
            document.open();
            
            com.lowagie.text.Font fontJudul = com.lowagie.text.FontFactory.getFont(com.lowagie.text.FontFactory.HELVETICA_BOLD, 16);
            com.lowagie.text.Paragraph judul = new com.lowagie.text.Paragraph("LAPORAN PENJUALAN HARIAN\n\n", fontJudul);
            judul.setAlignment(com.lowagie.text.Element.ALIGN_CENTER);
            document.add(judul);
            
            // Membuat tabel dengan 5 kolom
            com.lowagie.text.pdf.PdfPTable table = new com.lowagie.text.pdf.PdfPTable(5);
            table.setWidthPercentage(100);
            
            // Judul kolom
            String[] headers = {"No Transaksi", "Tanggal", "Total Belanja", "Bayar", "Kembalian"};
            for (String h : headers) {
                com.lowagie.text.pdf.PdfPCell cell = new com.lowagie.text.pdf.PdfPCell(new com.lowagie.text.Phrase(h));
                cell.setHorizontalAlignment(com.lowagie.text.Element.ALIGN_CENTER);
                cell.setBackgroundColor(java.awt.Color.LIGHT_GRAY);
                table.addCell(cell);
            }
            
            // Ambil data dari database
            java.sql.Connection conn = KoneksiDB.getKoneksi();
            java.sql.Statement stat = conn.createStatement();
            java.sql.ResultSet rs = stat.executeQuery("SELECT * FROM tb_transaksi ORDER BY tanggal DESC");
            
            while (rs.next()) {
                table.addCell(rs.getString("no_transaksi"));
                table.addCell(rs.getString("tanggal"));
                table.addCell(rs.getString("total_belanja"));
                table.addCell(rs.getString("bayar"));
                table.addCell(rs.getString("kembalian"));
            }
            document.add(table);
            document.close();
            
            javax.swing.JOptionPane.showMessageDialog(this, "Cetak Laporan Berhasil!\nFile: " + namaFile);
            
            // Langsung otomatis buka file PDF-nya
            java.awt.Desktop.getDesktop().open(new java.io.File(namaFile));
            
        } catch (Exception e) {
            if (document.isOpen()) document.close();
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal Mencetak: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new MenuUtama().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormLaporan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLaporan;
    // End of variables declaration//GEN-END:variables
}
