/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.kasirdigital;

/**
 *
 * @author IDEAPAD
 */
public class FormCheckout extends javax.swing.JFrame {
    javax.swing.table.DefaultTableModel keranjangDatang;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCheckout.class.getName());

    /**
     * Creates new form FormCheckout
     */
    public FormCheckout() {
     initComponents();
     getContentPane().setBackground(java.awt.Color.decode("#00BFFF"));
 }
    public FormCheckout(String totalBelanja, javax.swing.table.DefaultTableModel modelKeranjang) {
    initComponents();
    
    getContentPane().setBackground(java.awt.Color.decode("#00BFFF"));

    txtTotalBelanja.setText(totalBelanja);

    // Tampung data keranjang dari FormKasir ke variabel global kita
    this.keranjangDatang = modelKeranjang; 

    hitungPembayaran();
}

    private void hitungPembayaran() {
    try {
        int total = Integer.parseInt(txtTotalBelanja.getText());

        // Ambil angka diskon (jika kosong, anggap 0)
        int diskonPersen = 0;
        if (!txtDiskon.getText().isEmpty()) {
            diskonPersen = Integer.parseInt(txtDiskon.getText());
        }

        int nominalDiskon = (total * diskonPersen) / 100;
        int ppn = (total * 10) / 100;
        txtPpn.setText(String.valueOf(ppn));

        int grandTotal = total - nominalDiskon + ppn;
        txtGrandTotal.setText(String.valueOf(grandTotal));

        // Hitung kembalian jika uang bayar sudah diisi angka
        if (!txtBayar.getText().isEmpty()) {
            int bayar = Integer.parseInt(txtBayar.getText());
            int kembalian = bayar - grandTotal;
            txtKembalian.setText(String.valueOf(kembalian));
        } else {
            txtKembalian.setText("");
        }
    } catch (Exception e) {
        // Abaikan jika ada error ketik
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        txtTotalBelanja = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDiskon = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPpn = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtGrandTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtBayar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtKembalian = new javax.swing.JTextField();
        btnSelesai = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TOTAL BELANJA");

        txtTotalBelanja.setEditable(false);
        txtTotalBelanja.addActionListener(this::txtTotalBelanjaActionPerformed);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DISKON (%)");

        txtDiskon.addActionListener(this::txtDiskonActionPerformed);
        txtDiskon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiskonKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PPN (10%)");

        txtPpn.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("GRAND TOTAL");

        txtGrandTotal.setEditable(false);
        txtGrandTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtGrandTotal.addActionListener(this::txtGrandTotalActionPerformed);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("BAYAR");

        txtBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBayarKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("KEMBALI");

        txtKembalian.setEditable(false);

        btnSelesai.setBackground(new java.awt.Color(255, 153, 51));
        btnSelesai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSelesai.setForeground(new java.awt.Color(255, 255, 255));
        btnSelesai.setText("BAYAR");
        btnSelesai.addActionListener(this::btnSelesaiActionPerformed);

        btnBatal.setBackground(new java.awt.Color(255, 153, 51));
        btnBatal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("BATAL");
        btnBatal.addActionListener(this::btnBatalActionPerformed);

        btnCetak.setBackground(new java.awt.Color(255, 153, 51));
        btnCetak.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCetak.setForeground(new java.awt.Color(255, 255, 255));
        btnCetak.setText("CETAK STRUK");
        btnCetak.addActionListener(this::btnCetakActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PEMBAYARAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(btnSelesai))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTotalBelanja, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                                    .addComponent(txtDiskon)
                                    .addComponent(txtPpn)
                                    .addComponent(txtGrandTotal)
                                    .addComponent(txtBayar)
                                    .addComponent(txtKembalian)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(btnCetak)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addComponent(btnBatal)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTotalBelanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelesai)
                    .addComponent(btnCetak)
                    .addComponent(btnBatal))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalBelanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalBelanjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalBelanjaActionPerformed

    private void txtDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiskonActionPerformed

    private void txtGrandTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrandTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrandTotalActionPerformed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        try {
            java.sql.Connection conn = KoneksiDB.getKoneksi();
            
            // 1. Membuat Nomor Transaksi Otomatis berdasarkan Waktu (Unique)
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyyMMddHHmmss");
            String noTransaksi = "TRX-" + sdf.format(new java.util.Date());
            
            // 2. Simpan ke tabel tb_transaksi
            String sqlTransaksi = "INSERT INTO tb_transaksi VALUES (?, ?, ?, ?, ?)";
            java.sql.PreparedStatement pstTx = conn.prepareStatement(sqlTransaksi);
            pstTx.setString(1, noTransaksi);
            // Mengisi tanggal hari ini
            pstTx.setString(2, new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()));
            pstTx.setInt(3, Integer.parseInt(txtGrandTotal.getText()));
            pstTx.setInt(4, Integer.parseInt(txtBayar.getText()));
            pstTx.setInt(5, Integer.parseInt(txtKembalian.getText()));
            pstTx.execute();
            
            // 3. Looping isi keranjang untuk simpan ke tb_detail & POTONG STOK
            String sqlDetail = "INSERT INTO tb_detail VALUES (?, ?, ?, ?, ?)";
            String sqlUpdateStok = "UPDATE tb_barang SET stok = stok - ? WHERE kode_barang = ?";
            
            java.sql.PreparedStatement pstDt = conn.prepareStatement(sqlDetail);
            java.sql.PreparedStatement pstStok = conn.prepareStatement(sqlUpdateStok);
            
            for (int i = 0; i < keranjangDatang.getRowCount(); i++) {
                String kode = keranjangDatang.getValueAt(i, 0).toString();
                int harga = Integer.parseInt(keranjangDatang.getValueAt(i, 2).toString());
                int qty = Integer.parseInt(keranjangDatang.getValueAt(i, 3).toString());
                int subtotal = Integer.parseInt(keranjangDatang.getValueAt(i, 4).toString());
                
                // Set parameter untuk tb_detail
                pstDt.setString(1, noTransaksi);
                pstDt.setString(2, kode);
                pstDt.setInt(3, harga);
                pstDt.setInt(4, qty);
                pstDt.setInt(5, subtotal);
                pstDt.addBatch(); // Kumpulkan dulu
                
                // Set parameter untuk potong stok di tb_barang
                pstStok.setInt(1, qty);
                pstStok.setString(2, kode);
                pstStok.addBatch(); // Kumpulkan dulu
            }
            
            // Eksekusi semua data detail dan update stok secara massal (Batch)
            pstDt.executeBatch();
            pstStok.executeBatch();
            
            javax.swing.JOptionPane.showMessageDialog(this, "Transaksi Berhasil Disimpan!\nNomor: " + noTransaksi);
            
            // Mengosongkan keranjang asal karena transaksi sudah selesai
            keranjangDatang.setRowCount(0);
            this.dispose();
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memproses transaksi: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSelesaiActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        this.dispose(); // Hanya menutup form checkout, form keranjang tetap aman terbuka
    }//GEN-LAST:event_btnBatalActionPerformed

    private void txtDiskonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiskonKeyReleased
        hitungPembayaran();
    }//GEN-LAST:event_txtDiskonKeyReleased

    private void txtBayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBayarKeyReleased
        hitungPembayaran();
    }//GEN-LAST:event_txtBayarKeyReleased

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
       // Pakai ukuran kertas A5 agar menyerupai struk besar
        com.lowagie.text.Document document = new com.lowagie.text.Document(com.lowagie.text.PageSize.A5);
        try {
            // Pastikan uang bayar sudah diisi sebelum nyetak struk
            if (txtBayar.getText().isEmpty() || txtKembalian.getText().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Isi uang bayar terlebih dahulu sebelum cetak struk!");
                return;
            }

            String namaFile = "Struk_Belanja.pdf";
            com.lowagie.text.pdf.PdfWriter.getInstance(document, new java.io.FileOutputStream(namaFile));
            document.open();
            
            com.lowagie.text.Font fontJudul = com.lowagie.text.FontFactory.getFont(com.lowagie.text.FontFactory.HELVETICA_BOLD, 14);
            com.lowagie.text.Paragraph judul = new com.lowagie.text.Paragraph("STRUK PEMBELANJAAN\nKASIR DIGITAL ANNISA\n\n", fontJudul);
            judul.setAlignment(com.lowagie.text.Element.ALIGN_CENTER);
            document.add(judul);
            
            // Tabel berisi daftar barang (4 kolom)
            com.lowagie.text.pdf.PdfPTable table = new com.lowagie.text.pdf.PdfPTable(4);
            table.setWidthPercentage(100);
            table.addCell("Nama Barang");
            table.addCell("Harga");
            table.addCell("Qty");
            table.addCell("Subtotal");
            
            // Loop untuk mengambil data dari keranjang yang sedang tampil
            for (int i = 0; i < keranjangDatang.getRowCount(); i++) {
                table.addCell(keranjangDatang.getValueAt(i, 1).toString()); // Kolom Nama
                table.addCell(keranjangDatang.getValueAt(i, 2).toString()); // Kolom Harga
                table.addCell(keranjangDatang.getValueAt(i, 3).toString()); // Kolom Qty
                table.addCell(keranjangDatang.getValueAt(i, 4).toString()); // Kolom Subtotal
            }
            document.add(table);
            
            // Ringkasan harga di bagian bawah (rata kanan)
            com.lowagie.text.Paragraph ringkasan = new com.lowagie.text.Paragraph(
                "\n------------------------------------------------------" +
                "\nTotal Belanja : Rp " + txtTotalBelanja.getText() +
                "\nDiskon        : " + txtDiskon.getText() + "%" +
                "\nPPN (10%)     : Rp " + txtPpn.getText() +
                "\nGRAND TOTAL   : Rp " + txtGrandTotal.getText() +
                "\nUang Bayar    : Rp " + txtBayar.getText() +
                "\nKembalian     : Rp " + txtKembalian.getText() +
                "\n------------------------------------------------------" +
                "\n\nTerima Kasih Atas Kunjungan Anda!"
            );
            ringkasan.setAlignment(com.lowagie.text.Element.ALIGN_RIGHT);
            document.add(ringkasan);
            
            document.close();
            javax.swing.JOptionPane.showMessageDialog(this, "Cetak Struk Berhasil!");
            
            // Langsung buka struk PDF-nya
            java.awt.Desktop.getDesktop().open(new java.io.File(namaFile));
            
        } catch (Exception e) {
            if (document.isOpen()) document.close();
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal Mencetak Struk: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCheckout().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JTextField txtGrandTotal;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtPpn;
    private javax.swing.JTextField txtTotalBelanja;
    // End of variables declaration//GEN-END:variables
}
