/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.kasirdigital;

/**
 *
 * @author IDEAPAD
 */
public class MenuUtama extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuUtama.class.getName());

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        getContentPane().setBackground(java.awt.Color.decode("#00BFFF"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnMenuStok = new javax.swing.JButton();
        btnMenuTransaksi = new javax.swing.JButton();
        btnMenuLaporan = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEM KASIR DIGITAL");

        btnMenuStok.setBackground(new java.awt.Color(255, 153, 51));
        btnMenuStok.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuStok.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuStok.setText("MANAJEMEN STOK");
        btnMenuStok.addActionListener(this::btnMenuStokActionPerformed);

        btnMenuTransaksi.setBackground(new java.awt.Color(255, 153, 51));
        btnMenuTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuTransaksi.setText("MULAI TRANSAKSI");
        btnMenuTransaksi.addActionListener(this::btnMenuTransaksiActionPerformed);

        btnMenuLaporan.setBackground(new java.awt.Color(255, 153, 51));
        btnMenuLaporan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuLaporan.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuLaporan.setText("LAPORAN PENJUALAN");
        btnMenuLaporan.addActionListener(this::btnMenuLaporanActionPerformed);

        btnKeluar.setBackground(new java.awt.Color(255, 153, 51));
        btnKeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluar.setText("KELUAR");
        btnKeluar.addActionListener(this::btnKeluarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMenuTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMenuStok, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMenuLaporan)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnMenuStok)
                .addGap(39, 39, 39)
                .addComponent(btnMenuTransaksi)
                .addGap(39, 39, 39)
                .addComponent(btnMenuLaporan)
                .addGap(37, 37, 37)
                .addComponent(btnKeluar)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuLaporanActionPerformed
        new FormLaporan().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btnMenuLaporanActionPerformed

    private void btnMenuTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuTransaksiActionPerformed
        new FormKasir().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btnMenuTransaksiActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
     System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnMenuStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuStokActionPerformed
        new FormStok().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btnMenuStokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnMenuLaporan;
    private javax.swing.JButton btnMenuStok;
    private javax.swing.JButton btnMenuTransaksi;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
